language: scala

scala:
  - 2.10.4
  - 2.11.0

jdk:
  - oraclejdk7
  - oraclejdk8

script: sbt ++${TRAVIS_SCALA_VERSION} httpz/compile apache/compile apache/runTests dispatch/compile dispatch/runTests

